apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: apacheds
  name: test-users
  namespace: apacheds
data:
  data.ldif: |-
    dn: DC=domain,DC=com
    objectClass: domain
    dc: domain

    dn: ou=Users,DC=domain,DC=com
    objectClass: organizationalUnit
    ou: users


    dn: ou=Groups,DC=domain,DC=com
    objectClass: organizationalUnit
    ou: Groups


    dn: cn=ou_svc_account,ou=Users,DC=domain,DC=com
    objectClass: user
    cn: ou_svc_account
    givenName: ou
    sn: svc
    samAccountName: ou_svc_account
    userPassword: start123

    dn: cn=mmosley,ou=Users,DC=domain,DC=com
    objectClass: user
    cn: mmosley
    givenName: Matt
    sn: Mosley
    samAccountName: mmosley
    mail: mmosley@tremolo.dev
    title: Tester
    telephoneNumber: 123-456-7890
    userPassword: start123

    dn: cn=jjackson,ou=Users,DC=domain,DC=com
    objectClass: user
    cn: jjackson
    givenName: Jennifer
    sn: Jackson
    samAccountName: jjackson
    mail: jjackson@tremolo.dev
    title: Tester
    telephoneNumber: 123-456-7890
    userPassword: start123

   

    dn: cn=group1,ou=Groups,DC=domain,DC=com
    objectClass: group
    cn: group1
    member: cn=mmosley,ou=Users,DC=domain,DC=com

    dn: cn=group2,ou=Groups,DC=domain,DC=com
    objectClass: group
    cn: group2
    member: cn=mmosley,ou=Users,DC=domain,DC=com

